### ISSUE TITLE
Option to use a standalone ignore list

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#196]
Plex Discover is sporadic in terms of pulling in the correct metadata for certain series. For example seasons 2-7 of American greed aren't shown in plex discover. This leads to past episodes being scraped forever. I can ignore the entire show, but then future episodes won't be scraped. Adding an option to have the ignore list as a standalone local file would solve this.

**Comment by itsToggle** [comment]
implemented a the trakt watch status, aswell as an optional local file as "library ignore services". This update is currently in testing and is actively worked on, you could already check it out on the experimental branch. There will be bugs though.

**Comment by itsToggle** [comment]
alright, changes have been pushed. There is currently no check for wether or not the path exists - Id recommend using "./" as the path which should place an "ignored.txt" file into the same location of your "settings.json" file, once something is ignored. You can create that file yourself aswell, and fill it with the queries that should be ignored, seperated by new lines. Should look something like this:

    house.of.the.dragon
    last.week.tonight.with.john.oliver.S01.
    last.week.tonight.with.john.oliver.S02.
    last.week.tonight.with.john.oliver.S03.
    last.week.tonight.with.john.oliver.S04.
    last.week.tonight.with.john.oliver.S05.
    last.week.tonight.with.john.oliver.S06.
    last.week.tonight.with.john.oliver.S07.
    last.week.tonight.with.john.oliver.S08.
    south.park.S01E05.

**Comment by joshali1990** [comment]
Got the local ignore list to work, but when scraping it's not checking vs what's already in my plex library.

**Comment by itsToggle** [comment]
Hm you mind sharing a bit more info on your setup?
- What content service was the movie/show from that was scraped for but already on your server?
- what library collection service are you using?

**Comment by joshali1990** [comment]
The content service is my trakt collection, but I use my plex library as my library service. For example, the show the peripheral is already in my plex library, but is still being scraped. 

 done
[31/10/22 09:17:22] [plex] getting all watchlists ... done
[31/10/22 09:17:24] [trakt] getting all trakt lists ... done
[31/10/22 09:17:30] checking new content ... done
[31/10/22 09:17:30] scraping sources for query "the.peripheral.S01" ... done - found 208 releases
[31/10/22 09:17:34] scraping sources for query "the.peripheral.S01E01." ...

**Comment by itsToggle** [comment]
did you by any chance utilize the new "version trigger" feature Ive published a few minutes ago? Ive just fixed a little bug inside that feature that caused this to happen.

**Comment by itsToggle** [comment]
Oh and if you are using Trakt as your library collection service, only Trakt is checked for already existing content. If you haven't marked this show as "collected" on your Trakt account, plex_debrid will assume it's still missing.
If you are running a Plex server, I would recommend choosing Plex as your library collection service, so only content that's not on your Plex server will be downloaded.

**Comment by itsToggle** [comment]
Hm okay then, I'll try to reproduce that bug!

**Comment by joshali1990** [comment]
I think the issue has to do with how the plex library is read. I can't add my plex library as the ignore service at all. I go through the procress, but it doesn't save. Also removing one item from the local ignore list from within Plex_debrid removes all items with a similar name. For example removing last.week.tonight.s01. removes all items with last.week.tonight

**Comment by itsToggle** [comment]
Would you mind trying to add the plex discover watch status with the latest version?

That last bug should be an easy fix

**Comment by joshali1990** [comment]
Adding the plex ignore list works now, but it's still not taking my plex library items into account. I do not use any other library services.

**Comment by itsToggle** [comment]
Alright the removal of similar ingored titles should be fixed. 

I sadly cannot reproduce the issue that Trakt collection content is scraped for, eventhough it exists on the server.
Are you sure that you've set your "library collection service" to Plex and not Trakt?

**Comment by itsToggle** [comment]
Thanks for testing this out by the way, it's greatly appreciated!

**Comment by joshali1990** [comment]
Not pulling in the local ignore list now. Have it pointed to the correct path. Tried with and without a "/" at the end.

**Comment by itsToggle** [comment]
What did you enter into your local ignore list? Since I've removed the ability to match similar queries, you will need to enter the exact query that plex_debrid will use.

**Comment by joshali1990** [comment]
Nevermind it's populating now after restarting plex_debrid again. I'll troubleshoot the plex library issue and see if there's a setting I need to change or something.

**Comment by itsToggle** [comment]
I think ive found a possible solution, would you mind trying it again with the latest version?

**Comment by joshali1990** [comment]
Seems to be working, but the ignore list doesn't seem to be picking up everything. I copied exactly how plex_debrid is scraping for last week tonight and added it to the text file, but it doesn't appear on the ignore list. 
 
![image](https://user-images.githubusercontent.com/87837562/199041819-fde57ff4-5fc6-4a3f-982a-c4875c3beede.png)


![image](https://user-images.githubusercontent.com/87837562/199041946-f5f2b9d9-2ca3-4909-9dd4-46240f0610ba.png)

**Comment by itsToggle** [comment]
Yeah I limited the possibility for deviation, since that caused multiple ignored queries to be removed when you only wanted to remove one query (the issue you mentioned a couple of posts back).
I'll allow deviation when checking for ignored content, but won't allow it when removing ignored media :) I should have done that from the beginning, thank you!

**Comment by itsToggle** [comment]
alright, the ignore check will now allow for not-so-precise queries. You will still need to enter the exact tile though, but that should be alright :)
I think Im about done with testing and will probaply publish v2.20 on the main branch in a bit, so Ill close this issue :)

**Comment by joshali1990** [comment]
Seems to be that the ignore list is now combining all seasons into one item despite me having them all listed separately.

![image](https://user-images.githubusercontent.com/87837562/199061644-752a4bbc-f00b-4fc2-89cd-54f8b92f4d27.png)

**Comment by itsToggle** [comment]
Damn, yeah of course.. I think I can't allow for deviation then :/

The content of your "ignored.txt" file should still be the same though, it's just the "Ignored media" menu that shows the entire show as ignored. That's because the query for an entire show ("south.park") is of course part of the query for individual seasons ("south.park.S01"), and with my current method that's the only thing that's checked. I'll undo the latest changes, but that will mean you will need to add exact queries to successfully ignore content.

**Comment by joshali1990** [comment]
Thanks also still having the issue with the plex library not being accounted for. I think it might have to do with the way sections are checked, because when I specify which library sections to check I get the following error:

Type 'exit' to return to the main menu.
[31/10/22 13:00:36] [plex] getting plex library section/s "1,2" ... done
[31/10/22 13:00:43] [plex] getting all watchlists ... done
[31/10/22 13:00:46] [trakt] getting all trakt lists ... done
[31/10/22 13:00:53] checking new content ... done
[31/10/22 13:00:53] checking ignore status for item of type 'content.services.trakt' on service 'content.services.textfile'
[31/10/22 13:00:53] checking ignore status for item of type 'content.services.trakt' on service 'content.services.textfile'
Exception in thread Thread-1 (threaded):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/joshali/plex_debrid-main/ui/__init__.py", line 345, in threaded
    element.download(library=library)
  File "/Users/joshali/plex_debrid-main/content/classes.py", line 579, in download
    self.Seasons = self.uncollected(library)
  File "/Users/joshali/plex_debrid-main/content/classes.py", line 527, in uncollected
    if (not season.collected(list) or season.version_missing()) and not season.watched() and season.released() and not season.downloading():
  File "/Users/joshali/plex_debrid-main/content/classes.py", line 505, in collected
    if season.leafCount == self.leafCount:
AttributeError: 'media' object has no attribute 'leafCount'

**Comment by itsToggle** [comment]
Thanks!! That's truly incredible, I would have never caught that. The plex discover API returns a "leafCount" attribute for all seasons, when you request all libraries. When you only request specific libraries, that attribute is not returned. What the duck are they thinking.

I've fixed both issues you mentioned.

**Comment by itsToggle** [comment]
You should now be able to add less exact queries to the ignored.txt file. The deviation allowed is uppercase/lowercase and ending the query with a "." or not. So still pretty exact

**Comment by joshali1990** [comment]
You're amazing with updating so fast :). Still having the plex library check issue, but I'm just going to switch to trakt as my service.

**Comment by joshali1990** [comment]
Nevermind got it working by removing the specific section limitations. I'm sure you'll update the readme with instructions on this, but how do I use the new triggers? For example if I want to search 10 times for 1080 and then move to 720 what would I enter?

**Comment by joshali1990** [comment]
Sorry to keep bugging you. I think I isolated the issue with the plex library content to the easier service matching update. I assume trakt is not correctly matching with the id's in plex.

**Comment by itsToggle** [comment]
No problem at all, your testing is greatly appreciated. I can't find all bugs by myself, so I'm glad you are helping out before I make these changes public :)
Yeah I think so too, Ive just discovered a bug regarding the check of the "Plex discover watch status" for Trakt content. Matching the content is not working correctly, but I think I've narrowed down where it's going wrong.

**Comment by itsToggle** [comment]
Okay the matching issue regarding the watch status is fixed, any chance this fixed you library check aswell?

**Comment by joshali1990** [comment]
No, but I do get these errors when turning on debug printing. Not sure if that has something to do with it.

[31/10/22 15:26:52] [trakt] error: couldnt find seasons in show object
[31/10/22 15:26:52] [trakt] error: b'{"added":{"movies":0,"episodes":0},"updated":{"movies":0,"episodes":0},"existing":{"movies":0,"episodes":8},"not_found":{"movies":[],"shows":[],"seasons":[],"episodes":[],"people":[],"users":[]}}'

**Comment by itsToggle** [comment]
The second error is not crucial, its just telling you that the items that were supposed to be added to Trakt (either to the watch history or to your collection) were already there.

**Comment by itsToggle** [comment]
Okay so I cant reproduce the library check bug you are expiriencing. Ill make some last changes and then push the update now, so more people can test it. What plex metadata agent are you using?

**Comment by joshali1990** [comment]
Hmm,  can you try adding The peripheral to your trakt watchlist, letting it download and then reopening plex debrid? I’m using the default Tv and Movie agent.

**Comment by itsToggle** [comment]
![image](https://user-images.githubusercontent.com/71379623/199124675-aedd3b6b-5d74-40c9-8b78-be2895202989.png)
works from both the trakt watchlist, aswell as the trakt collection for me, are you sure you arent missing any episodes or something? :/

**Comment by joshali1990** [comment]
I’m out of ideas lol. Maybe my library’s too large or something. I’ll switch to the Trakt library for now. Thanks so much again for all your help!!

**Comment by itsToggle** [comment]
Perhaps with more people looking, we will find the issue :)

**Comment by itsToggle** [comment]
Alright this time I think Ive fixed it! :D I think ive found the bug. v2.21 should check the plex library correctly

**Comment by itsToggle** [comment]
If you are still having trouble, go to the Plex webUI and refresh the metadata for the shows/movies that are downloading eventhough you already have them on your server :)
